/*
 * Generated by gdbus-codegen 2.58.3 from object_manager.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef ___HOME_ROMAN_WORK_KUTASHENKO_BLE_PROVISION_SERVICE_LINUX_SRC_BLE_OBJMANAGER_GLUE_H__
#define ___HOME_ROMAN_WORK_KUTASHENKO_BLE_PROVISION_SERVICE_LINUX_SRC_BLE_OBJMANAGER_GLUE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.ObjectManager */

#define TYPE_DBUS_OBJECT_MANAGER (dbus_object_manager_get_type ())
#define DBUS_OBJECT_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_DBUS_OBJECT_MANAGER, DBusObjectManager))
#define IS_DBUS_OBJECT_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_DBUS_OBJECT_MANAGER))
#define DBUS_OBJECT_MANAGER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_DBUS_OBJECT_MANAGER, DBusObjectManagerIface))

struct _DBusObjectManager;
typedef struct _DBusObjectManager DBusObjectManager;
typedef struct _DBusObjectManagerIface DBusObjectManagerIface;

struct _DBusObjectManagerIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_managed_objects) (
    DBusObjectManager *object,
    GDBusMethodInvocation *invocation);

  void (*interfaces_added) (
    DBusObjectManager *object,
    const gchar *arg_object,
    GVariant *arg_interfaces);

  void (*interfaces_removed) (
    DBusObjectManager *object,
    const gchar *arg_object,
    const gchar *const *arg_interfaces);

};

GType dbus_object_manager_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *dbus_object_manager_interface_info (void);
guint dbus_object_manager_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void dbus_object_manager_complete_get_managed_objects (
    DBusObjectManager *object,
    GDBusMethodInvocation *invocation,
    GVariant *objects);



/* D-Bus signal emissions functions: */
void dbus_object_manager_emit_interfaces_added (
    DBusObjectManager *object,
    const gchar *arg_object,
    GVariant *arg_interfaces);

void dbus_object_manager_emit_interfaces_removed (
    DBusObjectManager *object,
    const gchar *arg_object,
    const gchar *const *arg_interfaces);



/* D-Bus method calls: */
void dbus_object_manager_call_get_managed_objects (
    DBusObjectManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean dbus_object_manager_call_get_managed_objects_finish (
    DBusObjectManager *proxy,
    GVariant **out_objects,
    GAsyncResult *res,
    GError **error);

gboolean dbus_object_manager_call_get_managed_objects_sync (
    DBusObjectManager *proxy,
    GVariant **out_objects,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_DBUS_OBJECT_MANAGER_PROXY (dbus_object_manager_proxy_get_type ())
#define DBUS_OBJECT_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_DBUS_OBJECT_MANAGER_PROXY, DBusObjectManagerProxy))
#define DBUS_OBJECT_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_DBUS_OBJECT_MANAGER_PROXY, DBusObjectManagerProxyClass))
#define DBUS_OBJECT_MANAGER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_DBUS_OBJECT_MANAGER_PROXY, DBusObjectManagerProxyClass))
#define IS_DBUS_OBJECT_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_DBUS_OBJECT_MANAGER_PROXY))
#define IS_DBUS_OBJECT_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_DBUS_OBJECT_MANAGER_PROXY))

typedef struct _DBusObjectManagerProxy DBusObjectManagerProxy;
typedef struct _DBusObjectManagerProxyClass DBusObjectManagerProxyClass;
typedef struct _DBusObjectManagerProxyPrivate DBusObjectManagerProxyPrivate;

struct _DBusObjectManagerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  DBusObjectManagerProxyPrivate *priv;
};

struct _DBusObjectManagerProxyClass
{
  GDBusProxyClass parent_class;
};

GType dbus_object_manager_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DBusObjectManagerProxy, g_object_unref)
#endif

void dbus_object_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DBusObjectManager *dbus_object_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
DBusObjectManager *dbus_object_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void dbus_object_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
DBusObjectManager *dbus_object_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
DBusObjectManager *dbus_object_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_DBUS_OBJECT_MANAGER_SKELETON (dbus_object_manager_skeleton_get_type ())
#define DBUS_OBJECT_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_DBUS_OBJECT_MANAGER_SKELETON, DBusObjectManagerSkeleton))
#define DBUS_OBJECT_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_DBUS_OBJECT_MANAGER_SKELETON, DBusObjectManagerSkeletonClass))
#define DBUS_OBJECT_MANAGER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_DBUS_OBJECT_MANAGER_SKELETON, DBusObjectManagerSkeletonClass))
#define IS_DBUS_OBJECT_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_DBUS_OBJECT_MANAGER_SKELETON))
#define IS_DBUS_OBJECT_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_DBUS_OBJECT_MANAGER_SKELETON))

typedef struct _DBusObjectManagerSkeleton DBusObjectManagerSkeleton;
typedef struct _DBusObjectManagerSkeletonClass DBusObjectManagerSkeletonClass;
typedef struct _DBusObjectManagerSkeletonPrivate DBusObjectManagerSkeletonPrivate;

struct _DBusObjectManagerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  DBusObjectManagerSkeletonPrivate *priv;
};

struct _DBusObjectManagerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType dbus_object_manager_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DBusObjectManagerSkeleton, g_object_unref)
#endif

DBusObjectManager *dbus_object_manager_skeleton_new (void);


G_END_DECLS

#endif /* ___HOME_ROMAN_WORK_KUTASHENKO_BLE_PROVISION_SERVICE_LINUX_SRC_BLE_OBJMANAGER_GLUE_H__ */
